[phases.setup]
cmds = [
    "apt-get update && apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev libonig-dev libxml2-dev libzip-dev",
    "docker-php-ext-configure gd --with-freetype --with-jpeg || true",
    "docker-php-ext-install -j$(nproc) gd mbstring pdo pdo_mysql xml zip || php -m"
]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = [
    "php artisan key:generate --force",
    "php artisan storage:link",
    "php artisan optimize:clear"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
